name: Deploy to Websupport

on:
  push:
    branches:
      - deploy

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.WEBSUPPORT_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add Websupport host key
        run: ssh-keyscan -p 27753 -H "${{ secrets.WEBSUPPORT_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          RSYNC_SRC="dist/"
          RSYNC_DEST="${{ secrets.WEBSUPPORT_USER }}@${{ secrets.WEBSUPPORT_HOST }}:studiokontura.com/sub/ronin"
          rsync -az --delete -e "ssh -p 27753 -i ~/.ssh/id_ed25519" "$RSYNC_SRC" "$RSYNC_DEST"

      - name: Cleanup
        run: rm -f ~/.ssh/id_ed25519